// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteArticle(arg1) {
  return window['go']['app']['App']['DeleteArticle'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['app']['App']['DeleteReport'](arg1);
}

export function DeleteUnitMeasure(arg1) {
  return window['go']['app']['App']['DeleteUnitMeasure'](arg1);
}

export function GetAllArticles() {
  return window['go']['app']['App']['GetAllArticles']();
}

export function GetAllReceptionsByArticleID(arg1) {
  return window['go']['app']['App']['GetAllReceptionsByArticleID'](arg1);
}

export function GetAllReportCompanies() {
  return window['go']['app']['App']['GetAllReportCompanies']();
}

export function GetAllReportPublishLocations() {
  return window['go']['app']['App']['GetAllReportPublishLocations']();
}

export function GetAllReportSignUsers() {
  return window['go']['app']['App']['GetAllReportSignUsers']();
}

export function GetAllReports() {
  return window['go']['app']['App']['GetAllReports']();
}

export function GetAllUnitMeasurements() {
  return window['go']['app']['App']['GetAllUnitMeasurements']();
}

export function GetNextReportCode() {
  return window['go']['app']['App']['GetNextReportCode']();
}

export function GetReportArticles(arg1) {
  return window['go']['app']['App']['GetReportArticles'](arg1);
}

export function GetReportTypes() {
  return window['go']['app']['App']['GetReportTypes']();
}

export function SaveArticle(arg1) {
  return window['go']['app']['App']['SaveArticle'](arg1);
}

export function SaveArticleReceptions(arg1, arg2) {
  return window['go']['app']['App']['SaveArticleReceptions'](arg1, arg2);
}

export function SaveReport(arg1) {
  return window['go']['app']['App']['SaveReport'](arg1);
}

export function SaveReportArticles(arg1, arg2) {
  return window['go']['app']['App']['SaveReportArticles'](arg1, arg2);
}

export function SaveUnitMeasure(arg1) {
  return window['go']['app']['App']['SaveUnitMeasure'](arg1);
}
