// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {article} from '../models';
import {report} from '../models';
import {unit} from '../models';

export function DeleteArticle(arg1:number):Promise<void>;

export function DeleteReport(arg1:number):Promise<void>;

export function DeleteUnitMeasure(arg1:number):Promise<void>;

export function GetAllArticles():Promise<Array<article.Article>>;

export function GetAllReceptionsByArticleID(arg1:number):Promise<Array<article.Reception>>;

export function GetAllReportCompanies():Promise<Array<string>>;

export function GetAllReportPublishLocations():Promise<Array<string>>;

export function GetAllReportSignUsers():Promise<Array<string>>;

export function GetAllReports():Promise<Array<report.Report>>;

export function GetAllUnitMeasurements():Promise<Array<unit.UnitMeasure>>;

export function GetNextReportCode():Promise<string>;

export function GetReportArticles(arg1:number):Promise<Array<report.Article>>;

export function GetReportTypes():Promise<Array<string>>;

export function SaveAllUnitMeasures(arg1:Array<unit.UnitMeasure>):Promise<void>;

export function SaveArticle(arg1:article.Article):Promise<void>;

export function SaveArticleReceptions(arg1:number,arg2:Array<article.Reception>):Promise<void>;

export function SaveReport(arg1:report.Report):Promise<void>;

export function SaveReportArticles(arg1:number,arg2:Array<report.Article>):Promise<void>;
