// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteArticle(arg1) {
  return window['go']['app']['WailsApp']['DeleteArticle'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['app']['WailsApp']['DeleteReport'](arg1);
}

export function DeleteUnitMeasure(arg1) {
  return window['go']['app']['WailsApp']['DeleteUnitMeasure'](arg1);
}

export function GetAllArticles() {
  return window['go']['app']['WailsApp']['GetAllArticles']();
}

export function GetAllCompanies() {
  return window['go']['app']['WailsApp']['GetAllCompanies']();
}

export function GetAllReceptionsByArticleID(arg1) {
  return window['go']['app']['WailsApp']['GetAllReceptionsByArticleID'](arg1);
}

export function GetAllReportPublishLocations() {
  return window['go']['app']['WailsApp']['GetAllReportPublishLocations']();
}

export function GetAllReports() {
  return window['go']['app']['WailsApp']['GetAllReports']();
}

export function GetAllUnitMeasurements() {
  return window['go']['app']['WailsApp']['GetAllUnitMeasurements']();
}

export function GetAllUserNames() {
  return window['go']['app']['WailsApp']['GetAllUserNames']();
}

export function GetNextReportCode() {
  return window['go']['app']['WailsApp']['GetNextReportCode']();
}

export function GetReportArticles(arg1) {
  return window['go']['app']['WailsApp']['GetReportArticles'](arg1);
}

export function GetReportTypes() {
  return window['go']['app']['WailsApp']['GetReportTypes']();
}

export function SaveAllUnitMeasures(arg1) {
  return window['go']['app']['WailsApp']['SaveAllUnitMeasures'](arg1);
}

export function SaveArticle(arg1, arg2) {
  return window['go']['app']['WailsApp']['SaveArticle'](arg1, arg2);
}

export function SaveReport(arg1, arg2) {
  return window['go']['app']['WailsApp']['SaveReport'](arg1, arg2);
}
