// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {article} from '../models';
import {company} from '../models';
import {report} from '../models';
import {unit} from '../models';

export function DeleteArticle(arg1:number):Promise<void>;

export function DeleteReport(arg1:number):Promise<void>;

export function DeleteUnitMeasure(arg1:number):Promise<void>;

export function GetAllArticles():Promise<Array<article.Article>>;

export function GetAllCompanies():Promise<Array<company.Company>>;

export function GetAllReceptionsByArticleID(arg1:number):Promise<Array<article.Recipe>>;

export function GetAllReportPublishLocations():Promise<Array<string>>;

export function GetAllReports():Promise<Array<report.Report>>;

export function GetAllUnitMeasurements():Promise<Array<unit.UnitMeasure>>;

export function GetAllUserNames():Promise<Array<string>>;

export function GetNextReportCode():Promise<string>;

export function GetReportArticles(arg1:number):Promise<Array<report.ReportArticle>>;

export function GetReportTypes():Promise<Array<report.ReportType>>;

export function SaveAllUnitMeasures(arg1:Array<unit.UnitMeasure>):Promise<void>;

export function SaveArticle(arg1:article.Article,arg2:Array<article.Recipe>):Promise<void>;

export function SaveReport(arg1:report.Report,arg2:Array<report.ReportArticle>):Promise<void>;
